apiVersion: v1
kind: ConfigMap
metadata:
  name: upload-html
data:
  upload.html: |
    <html>
    <body>
      <h1>Upload Image</h1>
      <form method="POST" action="http://backend-api-svc:5000/upload" enctype="multipart/form-data">
        <input type="file" name="file" />
        <input type="submit" value="Upload" />
      </form>
    </body>
    </html>
