apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: logging
spec:
  type: NodePort
  ports:
  - port: 5044
    targetPort: 5044
    nodePort: 32000  # <== This will be accessed via NodeIP:32000
  selector:
    app: logstash
